
package com.microstream.bookstore.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;

import com.microstream.bookstore.domain.Purchaseitem;
import com.rapidclipse.framework.server.jpa.dal.JpaDataAccessObject;


/**
 * Home object for domain model class Purchaseitem.
 *
 * @see Purchaseitem
 */
public class PurchaseitemDAO extends JpaDataAccessObject.Default<Purchaseitem, Long>
{
	public final static PurchaseitemDAO INSTANCE = new PurchaseitemDAO();

	public PurchaseitemDAO()
	{
		super(Purchaseitem.class);
	}
	
	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<Purchaseitem> avgprice()
	{
		final CriteriaQuery<Purchaseitem> criteriaQuery = this.avgpriceQuery();

		final EntityManager entityManager = this.em();

		final TypedQuery<Purchaseitem> query = entityManager.createQuery(criteriaQuery);
		return query.getResultList();
	}
	
	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public CriteriaQuery<Purchaseitem> avgpriceQuery()
	{
		final EntityManager entityManager = this.em();

		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();

		final CriteriaQuery<Purchaseitem> criteriaQuery = criteriaBuilder.createQuery(Purchaseitem.class);

		criteriaQuery.from(Purchaseitem.class);

		return criteriaQuery;
	}
}
